//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLM {
	
	
	public partial class emailConfirm {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtCode;
		
		protected System.Web.UI.WebControls.Button btnOK;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl pResult;
	}
}
