//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLM {
	
	
	public partial class test_usr {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox tbUid;
		
		protected System.Web.UI.WebControls.TextBox tbULogin;
		
		protected System.Web.UI.WebControls.TextBox tbUEmail;
		
		protected System.Web.UI.WebControls.TextBox tbUName;
		
		protected System.Web.UI.WebControls.TextBox tbUPass;
		
		protected System.Web.UI.WebControls.TextBox tbUFlag;
		
		protected System.Web.UI.WebControls.Button btnUCreate;
		
		protected System.Web.UI.WebControls.Button btnUpdate;
		
		protected System.Web.UI.WebControls.Button btnUread;
	}
}
