//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLM {
    
    
    public partial class wucUserSelector {
        
        protected System.Web.UI.HtmlControls.HtmlTable tblComponent;
        
        protected System.Web.UI.WebControls.DropDownList DDLUserTypes;
        
        protected System.Web.UI.WebControls.TextBox tbSearch;
        
        protected System.Web.UI.WebControls.Button btnSearch;
        
        protected System.Web.UI.WebControls.Label lblRows;
        
        protected System.Web.UI.HtmlControls.HtmlGenericControl divGridList;
        
        protected System.Web.UI.WebControls.GridView grdUsers;
        
        protected System.Web.UI.WebControls.HiddenField hBtnIndSel;
        
        protected System.Web.UI.HtmlControls.HtmlGenericControl buttonsPP;
        
        protected System.Web.UI.WebControls.SqlDataSource UsersSource;
    }
}
